server:
 port: 9200
 context-path: /oms-web

spring:
 devtools:
  restart:
   exclude: static/**
   enabled: true
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  url: jdbc:mysql://172.168.20.8:3306/bright-oms?useUnicode=true&characterEncoding=utf8
  driverClassName: com.mysql.jdbc.Driver
  username: root
  password: '@qi8jb#1'
 session:
   store-type: redis
 redis:
  host: localhost 
  port: 6379
  password: lsh0904
  timeout: 10000
 thymeleaf:
  cache: false
  mode: LEGACYHTML5
 jackson:
  serialization:
   FAIL_ON_EMPTY_BEANS: false

mybatis:
  mapperLocations: /mapper/**/*Mapper.xml




user:
 details:
  sql:
   userQuery: select phone as username,passwd as password,enabled as enabled from sys_user where phone = ?
   authoritiesQuery: SELECT DISTINCT su. NAME AS username , sa.role AS authority FROM sys_user_group AS sug JOIN sys_group_authority AS sga ON sug.group_id = sga.group_id JOIN sys_authority AS sa ON sga.authority_id = sa.id JOIN sys_group AS sg ON sga.group_id = sg.id JOIN sys_user AS su ON su.id = sug.user_id WHERE su.phone = ? AND sg.enabled = 1




api:
  list:
   - appId: userCenter
     url: http://172.168.20.8:8090/
     credential: client:oauthchuangmjclient
     grantType: client_credentials
   - appId: sms-api
     url: http://172.168.20.8:9120/
     credential: client:client
     grantType: client_credentials
   - appId: oss-client
     url: http://oss.platform.liangshenghuo.cn/
     credential: client:oauthchuangmjclient
     grantType: client_credentials


logging:
 level:
  root: info
  com.bright.oms.mapper: trace






